INSERT INTO APPLICATION_USER VALUES
(5, 'F', 'P');
--
--INSERT INTO WORKOUT (WORKOUT_ID, UUID, DURATION, TIME_STAMP, CAL, APPLICATION_USER_APPLICATION_USER_ID) VALUES
--(1, 1, 1, 1.0, 1, 5);

INSERT INTO WORKOUT_TYPE (TYPE_ID, UUID, TYPE_CODE, HAS_SNAPSHOTS) VALUES
(1, '1', 1, 'true');

INSERT INTO TYPE_ARGUMENT  (TYPE_ARGUMENT_ID, NAME, WORKOUT_TYPE_TYPE_ID) VALUES
(1, 'distance', 1)

